








kind: Service
apiVersion: v1
metadata:
  name: liferay-service-dev
  labels:
    app: liferay
    tier: frontend
    env: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    role: frontend
    app: liferay
<<<<<<< HEAD:kubernetes-liferay/DEV/liferay-service.yaml
    env: dev
=======
>>>>>>> 5abcb417700003117f88b323296cb32f3c8330a4:kubernetes-liferay/liferay-service.yaml
