kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: liferay-data-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: liferay-deploy-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi