








kind: Service
apiVersion: v1
metadata:
  name: liferay-service
  labels:
    app: liferay
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
    targetPort: 8080
  selector:
    role: frontend
    app: liferay